### ISSUE TITLE
Tooltips for Sensor Data + Checkmarks for Sensor Data

### ISSUE THREAD

**Issue by a-pasquale** [tgb20/Hermes#14]
Units label for tof sensor is cm. Is that correct? Seems like it should be time.

Sensor units for barometer should be millibars (mb).

**Comment by tgb20** [comment]
I took all units from Tellos documentation: https://dl-cdn.ryzerobotics.com/downloads/tello/20180910/Tello%20SDK%20Documentation%20EN_1.3.pdf

The ToF sensor measures the estimated distance to the ground from the downward facing camera, it's a Time of Flight Camera labeled as `ToF`, the actual time of flight is reported in `time`.

**Comment by tgb20** [comment]
I think you have ToF and height backwards, but I see the descriptions in the v2 documentation.
