### ISSUE TITLE
Start and stop video blocks do not work

### ISSUE THREAD

**Issue by tgb20** [tgb20/Hermes#40]
The blocks to start and stop video recording are not functioning. I will update this when I have tested the start and stop video buttons in the dash board.

**Comment by a-pasquale** [comment]
I added the onclick functions for the photo and video control buttons and they are working again. See commit 213e699bc. The code blocks also worked when I tested them. Can you confirm this is still not working?

**Comment by tgb20** [comment]
Both the buttons and the blocks are now functioning correctly.
