### ISSUE TITLE
Socket webContents Error on Windows

### ISSUE THREAD

**Issue by a-pasquale** [tgb20/Hermes#42]
This error happens when closing app on Windows:
![Annotation 2020-06-11 222254](https://user-images.githubusercontent.com/539763/84458240-8c469680-ac32-11ea-8795-31697db372f3.png)

It seems to only happen after you have been connected to the drone. If you close the app without connecting, there is no error message.

**Comment by a-pasquale** [comment]
This also happened on Mac if I quite when connected, though I only get one error box. On Windows, I'm unable to quit because errors keep coming.

**Comment by a-pasquale** [comment]
This issue is just an annoyance on Mac but is a release blocker on Windows. You have to close the app through task manager. We should fix this before publishing the Windows build.

**Comment by tgb20** [comment]
There was an error with an if statement that made sure the UI wasn't being updated after it has been dismissed. I have fixed this with commit [db13ef1
](https://github.com/tgb20/Hermes/commit/db13ef10cb3f65056fa3af63b5376792469d4d94). Let me know if the error still occurs.
