### ISSUE TITLE
Default menu item in Windows

### ISSUE THREAD

**Issue by a-pasquale** [tgb20/Hermes#43]
![Annotation 2020-06-12 164756](https://user-images.githubusercontent.com/539763/84545076-94531480-accc-11ea-920c-e1d605f7e2f5.png)

Seems like the Windows build has an extra menu item.

**Comment by tgb20** [comment]
Fixed with [db13ef1](https://github.com/tgb20/Hermes/commit/8ae9e8079630b37737f79dfb9c6ea4b1d869cde0)
